version: '3'
services:
  ops-pilot:
    image: ccr.ccs.tencentyun.com/megalab/ops-pilot
    container_name: ops-pilot
    restart: always
    volumes:
      - ./conf/credentials.yml:/apps/credentials.yml
      - ./conf/endpoints.yml:/apps/endpoints.yml
    command:
      - rasa 
      - run 
      - --enable-api 
      - --cors 
      - "*"
    ports:
      - 5005:5005    

  ops-pilot-action-server:
    image: ccr.ccs.tencentyun.com/megalab/ops-pilot
    container_name: ops-pilot-action-server
    restart: always
    environment:
      - AZURE_OPENAI_MODEL_NAME=${AZURE_OPENAI_MODEL_NAME}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_KEY=${AZURE_OPENAI_KEY}
      - RUN_MODE=PROD
    volumes:
      - ./conf/credentials.yml:/apps/credentials.yml
      - ./conf/endpoints.yml:/apps/endpoints.yml
    command:
      - rasa 
      - run 
      - actions

