version: '3'
services:
  ops-pilot:
    image: ccr.ccs.tencentyun.com/megalab/ops-pilot
    container_name: ops-pilot
    restart: always
    volumes:
      - ./conf/credentials.yml:/apps/credentials.yml
      - ./conf/endpoints.yml:/apps/endpoints.yml
    command:
      - rasa 
      - run 
      - --enable-api 
      - --cors 
      - "*"
    ports:
      - 5005:5005    

  ops-pilot-action-server:
    image: ccr.ccs.tencentyun.com/megalab/ops-pilot
    container_name: ops-pilot-action-server
    restart: always
    environment:
      - OPENAI_ENDPOINT=${OPENAI_ENDPOINT}
      - OPENAI_KEY=${OPENAI_KEY}
      - RUN_MODE=PROD
      - VEC_DB_PATH=vec_db
      - CHAT_MODE=knowledgebase
      - FALLBACK_PROMPT=扮演专业的运维工程师
      - FALLBACK_LLM=OPENAI
    volumes:
      - ./conf/credentials.yml:/apps/credentials.yml
      - ./conf/endpoints.yml:/apps/endpoints.yml
    command:
      - rasa 
      - run 
      - actions

